import {
  Baby,
  Image,
  Quote,
  CalendarDays,
  HeartPulse,
  FolderOpen,
  Receipt,
  Calculator,
  FileText,
  StickyNote,
  Settings,
} from "lucide-react";

export const sections = [
  {
    id: "children",
    title: "Profil enfant",
    description: "Photos, école, rappels, santé.",
    icon: Baby,
    bg: "bg-[#fff3f6]",
    border: "border-[#f4c9d5]",
    iconBg: "bg-[#e99aaa]",
  },
  {
    id: "photos",
    title: "Photos",
    description: "Souvenirs et albums.",
    icon: Image,
    bg: "bg-[#fff4f0]",
    border: "border-[#efcabc]",
    iconBg: "bg-[#df9f8a]",
  },
  {
    id: "memorable-phrases",
    title: "Phrases mémorables",
    description: "Citations et mots d’enfants.",
    icon: Quote,
    bg: "bg-[#fff7fb]",
    border: "border-[#f0cfe0]",
    iconBg: "bg-[#d99ab9]",
  },
  {
    id: "calendar",
    title: "Calendrier",
    description: "Gardes, activités, rendez-vous.",
    icon: CalendarDays,
    bg: "bg-[#f7fbf3]",
    border: "border-[#d8e6ca]",
    iconBg: "bg-[#a8b58f]",
  },
  {
    id: "sante",
    title: "Médical",
    description: "Santé et médicaments.",
    icon: HeartPulse,
    bg: "bg-[#f4fbf8]",
    border: "border-[#c8e4d8]",
    iconBg: "bg-[#8fbfa8]",
  },
  {
    id: "documents",
    title: "Zone documents",
    description: "Ententes et formulaires.",
    icon: FolderOpen,
    bg: "bg-[#fff9ef]",
    border: "border-[#ead7b8]",
    iconBg: "bg-[#d8b77f]",
  },
  {
    id: "invoices",
    title: "Factures / reçus",
    description: "Dépenses et paiements.",
    icon: Receipt,
    bg: "bg-[#f8f5ff]",
    border: "border-[#d8cef1]",
    iconBg: "bg-[#aa99cf]",
  },
  {
    id: "calculator",
    title: "Calculateur de journées",
    description: "Répartition annuelle.",
    icon: Calculator,
    bg: "bg-[#f1f7ff]",
    border: "border-[#c6daf4]",
    iconBg: "bg-[#9ebbe1]",
  },
  {
    id: "parental-plan",
    title: "Plan parental",
    description: "Horaire, décisions, ententes.",
    icon: FileText,
    bg: "bg-[#f7f3ff]",
    border: "border-[#d9cdf4]",
    iconBg: "bg-[#ad9bcf]",
  },
  {
    id: "notes",
    title: "Zone notes",
    description: "Rappels et suivis.",
    icon: StickyNote,
    bg: "bg-[#fffdf3]",
    border: "border-[#eadfac]",
    iconBg: "bg-[#d7c37f]",
  },
  {
    id: "settings",
    title: "Paramètres",
    description: "Compte et accès.",
    icon: Settings,
    bg: "bg-[#f5f5f2]",
    border: "border-[#d8d8cd]",
    iconBg: "bg-[#a9aa91]",
  },
];